name: 'execute action'
description: 'create a container that creates the container to execute an action'
inputs:
  # each os-specific container executes common.sh as the entrypoint script. common.sh
  # executes this script with the remaining arguments. this allows the the containers
  # to execute arbitrary scripts, at this time node-os-tests.sh or publish.sh.
  script-to-run:
    description: 'specify the script that the os-specific container should run'
    required: true

  node-image:
    description: 'docker image that will be used to build the test container'
  branch-to-test:  # id of input
    description: 'which branch in the repo should be tested'
    required: true
    default: 'master'
  ao-token-prod:
    description: 'appoptics token valid in production environment'
    required: true

  # the following are required but only used when script-to-run is publish.sh
  aws-access-key-id:
    description: 'aws access key for publishing pre-built bindings'
    required: true
    default: ''
  aws-secret-access-key:
    description: 'aws secret access key for publishing pre-built bindings'
    required: true
    default: ''

runs:
  using: 'docker'
  image: 'generic.Dockerfile'
  # these must be in the same order as they are expected in entrypoint.sh
  args:
    - ${{inputs.script-to-run}}
    - ${{inputs.node-image}}
    - ${{inputs.branch-to-test}}
    - ${{inputs.ao-token-prod}}

    - ${{inputs.aws-access-key-id}}
    - ${{inputs.aws-secret-access-key}}

