# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  branch-to-test:  # id of input
    description: 'which branch in the repo should be tested'
    required: true
    default: 'master'
  ao-token-prod:
    description: 'appoptics token valid in production environment'
    required: true
outputs:
  install-prod:
    description: 'production installation result'
  install-dev:
    description: 'development installation result'
  tests-passed-count:
    description: 'number of tests that succeeded'
  tests-failed-count:
    description: 'number of tests that failed'
  tests-failed:
    description: 'tests that failed'
runs:
  using: 'docker -u root'
  image: 'centos.Dockerfile'
  args:
    - ${{inputs.branch-to-test}}
    - ${{inputs.ao-token-prod}}
