name: Fallback Install, Build & Package & Prebuilt Install (Merge)

on: 
  push: 
    branches: 
      # triggered by pull request approval triggers which is a merge to default branch
      - master

  workflow_dispatch:
    inputs: 
      target-test:
        required: false
        description: 'Run Tests on Target & Fallback Groups? (type: yes)'
        default: false

jobs:
  # both build-group-unpublish and  build-group-publish "needs" this job
  load-build-group:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout ${{ github.ref }}
      uses: actions/checkout@v2

      # build with the lowest versions of the OSes supported so the glibc/musl versions are the oldest/most compatible. 
      # note: some of those images are no longer supported officially (https://hub.docker.com/_/node)
    - name: Load build group data
      id: set-matrix
      run: .github/scripts/matrix-from-json.sh .github/config/build-group.json

  build-group-unpublish:
    runs-on: ubuntu-latest 
    needs: load-build-group
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.load-build-group.outputs.matrix)}}
    container:
        image:  ${{ matrix.image }}

    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Show Environment Info
        run: |
          printenv
          node --version
          npm --version 
          cat /etc/os-release

      # must install specific dependencies before a build
      # can't call npm install. doing so may fallback-to-build if package has yet to be published (double build)
      # use npm workaround specifying a package name to bypass install script in package.json
      - name: NPM Install dependencies
        run: npm install linux-os-info --unsafe-perm

      - name: Clear Staging for version
        run: npx node-pre-gyp unpublish --s3_host=staging

  load-fallback-group:
    runs-on: ubuntu-latest
    needs: build-group-unpublish
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout ${{ github.ref }}
      uses: actions/checkout@v2

      # contains images that are able to build "out of the box"
    - name: Load target group data
      id: set-matrix
      run: .github/scripts/matrix-from-json.sh .github/config/fallback-group.json

  fallback-group-install:
    runs-on: ubuntu-latest
    needs: load-fallback-group
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.load-fallback-group.outputs.matrix)}}
    container:
        image: ${{ matrix.image }}

    env:
      # TODO: move to staging when AO-20147
      AO_TOKEN_PROD: ${{ secrets.AO_TOKEN_PROD }}

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Show Environment Info
        run: |
          printenv
          node --version
          npm --version 
          cat /etc/os-release

      # the staging bucket has been cleared
      # install of package will fallback to build from source
      - name: NPM Install (to fallback)
        run: npm install --unsafe-perm --s3_host=staging

      - name: Check Artifacts
        run: ls ./dist/napi-v*/apm_bindings.node && ls ./dist/napi-v*/ao_metrics.node

      - name: Run tests
        run: npm test
        if: ${{ github.event.inputs.target-test }}

  build-group-publish:
    runs-on: ubuntu-latest 
    needs: [load-build-group, fallback-group-install]
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.load-build-group.outputs.matrix)}}
    container:
        image:  ${{ matrix.image }}

    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Show Environment Info
        run: |
          printenv
          node --version
          npm --version 
          cat /etc/os-release

      # must install specific dependencies before a build
      # can't call npm install. doing so may fallback-to-build if package has yet to be published (double build)
      # use npm workaround specifying a package name to bypass install script in package.json
      - name: NPM Install dependencies
        run: npm install linux-os-info --unsafe-perm

      # must setup libobo before build
      # node-pre-gyp rebuild runs "clean" and "build" at once.
      # it is mapped to `node-gyp rebuild` which internally means "clean + configure + build" and triggers a full recompile
      - name: Build
        run: |
          node setup-liboboe.js
          npx node-pre-gyp rebuild

      # artifacts are at:build/stage/nodejs/bindings/
      - name: Package
        run: npx node-pre-gyp package # requires clean rebuild

      # *** IMPORTANT: 
      # always include --s3_host flag regardless of node-pre-gyp defaults.
      # node-pre-gyp can't publish over existing version, thus always attempt unpublished of current in staging bucket
      - name: Clear Staging for version
        run: npx node-pre-gyp unpublish --s3_host=staging

      - name: Publish Package to Staging
        run: npx node-pre-gyp publish --s3_host=staging

  load-prebuilt-group:
    runs-on: ubuntu-latest
    needs: build-group-publish
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout ${{ github.ref }}
      uses: actions/checkout@v2

      # contains images that are unable to build "out of the box" and will install prebuilt
    - name: Load target group data
      id: set-matrix
      run: .github/scripts/matrix-from-json.sh .github/config/prebuilt-group.json

  prebuilt-group-install:
    runs-on: ubuntu-latest 
    needs: load-prebuilt-group
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.load-prebuilt-group.outputs.matrix)}}
    container:
        image: ${{ matrix.image }}

    env:
      # TODO: move to staging when AO-20147
      AO_TOKEN_PROD: ${{ secrets.AO_TOKEN_PROD }}

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Show Environment Info
        run: |
          printenv
          node --version
          npm --version 
          cat /etc/os-release

      # *** IMPORTANT: by default our package is installed from production bucket as defined in package.json. 
      # to test current build pass --s3_host="staging"
      - name: NPM Install Staging
        run: npm install --unsafe-perm --s3_host=staging

      - name: Check Artifacts
        run: ls ./dist/napi-v*/apm_bindings.node && ls ./dist/napi-v*/ao_metrics.node

      - name: Run tests
        run: npm test
        if: ${{ github.event.inputs.target-test }}
