name: os-tests for alpine and centos

# https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359
on:
  # manual trigger
  workflow_dispatch:
  # most pushes to master are the result of a pull request, so this is effectively
  # "on pull_request merge to master"
  push:
    branches:
      - gh-actions-2
      - master

jobs:
  test-image-builder:
    strategy:
      matrix:
        os-version: [
        #'node:10-alpine3.9', 'node:10-alpine3.10', 'node:10-alpine3.11',
        #'node:12-alpine3.9', 'node:12-alpine3.10', 'node:12-alpine3.11', 'node:12-alpine3.12',
        #'node:14-alpine3.10', 'node:14-alpine3.11', 'node:14-alpine3.12',
        'node:15-alpine3.12',
        #'centos:7+node:10', 'centos:8+node:10',
        #'centos:7+node:12', 'centos:8+node:12',
        #'centos:7+node:14', 'centos:8+node:14',
        'centos:8+node:15'
        ]
    runs-on: ubuntu-latest
    # (os-version) is appended, so "test" appears "test (node:10-alpine3.9)"
    name: test
    steps:
    # To use a repo-specific action you must check out the repository
    - name: Checkout to root dir
      uses: actions/checkout@v2
    - name: Create specific alpine/node image
      id: generic
      uses: ./.github/actions/generic
      with:
        branch-to-test: 'gh-actions-2'
        ao-token-prod: ${{secrets.AO_TOKEN_PROD}}
        node-image: ${{matrix.os-version}}
    # Use the output from the `generic` step
    - name: show arguments from 1st & 2nd scripts and os details
      run: |
        echo "all args 1 ${{steps.generic.outputs.all-args}}"
        echo "all args 2 ${{steps.generic.outputs.all-args-2}}"
        echo "os ${{steps.generic.outputs.os-details}}
        echo "branch ${{steps.generic.outputs.branch-to-test}}"
    - name: test results
      run: |
        echo "npm install --production --unsafe-perm ${{steps.generic.outputs.install-prod}}"
        echo "npm install --unsafe-perm ${{steps.generic.outputs.install-dev}}"
        echo "tests passed ${{steps.generic.outputs.tests-passed-count}}"
        echo "tests failed ${{steps.generic.outputs.tests-failed-count}} - ${{steps.generic.outputs.tests-failed}}"
