name: Prep - Build Docker Images (manual)

on:
  # TODO: revisit.
  # as of July 2021, there seems to be a GitHub Actions bug causing this workflow to run when a tag is pushed.
  # adding tags-ignore: causes the workflow to not run at all.
  # since tag push is used for release trigger, decision was made to build images using manual trigger only.

  # push:
  #   paths:
  #     - '.github/docker-node/*.Dockerfile'

  workflow_dispatch:

jobs:
  load-docker-node:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout ${{ github.ref }}
      uses: actions/checkout@v2

      # comments for: docker-node.json
    - name: Load build group data
      id: set-matrix
      run: .github/scripts/matrix-from-json.sh .github/config/docker-node.json

  build-push:
    name: Build docker images
    runs-on: ubuntu-latest
    needs: load-docker-node

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.load-docker-node.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./.github/docker-node/
          file: ./.github/docker-node/${{ matrix.tag }}.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/node:${{ matrix.tag }}
